### ISSUE TITLE
about database

### ISSUE THREAD

**Issue by pcmg12138** [nii-yamagishilab/Capsule-Forensics-v2#10]
hi，How do I set up the dataset, like if I need to detect multiple videos and crop each video as a frame into a folder? Do you have a special naming format for the frames captured from each video？

**Comment by honghuy127** [comment]
Hi, for training, there is no requirement for naming the frames. We treated them as images. For evaluation, you need to write your own script.

**Comment by pcmg12138** [comment]
hello For multiple videos, just put the cropped face image into the corresponding folder

**Comment by pcmg12138** [comment]
hello For multiple videos, just put the cropped face image into the corresponding folder?

**Comment by pcmg12138** [comment]
如果我有多个视频 放在同个文件夹下（如 0_original），检测的时候怎么进行区分视频数量

**Comment by pcmg12138** [comment]
If I have more than one video in the same folder (e.g. 0_original), how can I distinguish the number of videos when checking

**Comment by honghuy127** [comment]
You could not reuse this script. Instead, you need to write the new one which could deal with videos (which includes multiple frames). One possible solution is adding a counter to the file name and writing a new data loader.
