### ISSUE TITLE
about .txt files

### ISSUE THREAD

**Issue by ichv16** [nii-yamagishilab/Capsule-Forensics-v2#11]
Hi! I just started learning this project a few days ago,and I'm really confused about how to use it.
Firstly,I wonder whether  the txt file like 'test_detail.txt' needs to be created by myself.
Secondly,I have loaded the FaceForensics-master dataset but I don't know how to start. 
My questions may be too simple, however,I'm stuck in this dilemma.Would you please resolve my confusion?

**Comment by honghuy127** [comment]
No, you don't need to create the test_detail.txt by yourself. Instead, please create a folder which includes this file. You can modify the python script to automatically check and create this folder for you in the case it does not exist.

The dataset class we used in this paper is the PyTorch folder dataset. There are several sub-folders, each of them corresponds to a label. You can put pre-processed images into these sub-folder.
