### ISSUE TITLE
about output

### ISSUE THREAD

**Issue by ninohan** [nii-yamagishilab/Capsule-Forensics-v2#12]
Hi:
Thanks for this great job. I would like to ask why the larger output of the capsule network (class_ in the code) stays between 0.5-0.8 (usually about 0.7) and not greater than 0.9. Is it possible to make it greater than 0.9 and how to do it.

**Comment by honghuy127** [comment]
Hi, the output of the capsule network is the mean of the probabilities in each dimension of the output vector, therefore it is usually between [0.5, 0.8] and is hard to reach 0.9. Maybe you can scale it a little bit and apply clipping to prevent it to be greater than 1.

**Comment by ninohan** [comment]
Thanks for your answer and inspiration and I have achieved through the margin loss.
