### ISSUE TITLE
multi-GPU training

### ISSUE THREAD

**Issue by 1234273** [nii-yamagishilab/Capsule-Forensics-v2#16]
Hi,I would like to know how to modify the code in the model to achieve multi-gpu training.please.

**Comment by honghuy127** [comment]
Hi, you can only apply multi-gpu training on the feature extractor part.
For the capsule part, it's really complicated to modify the dynamic routing algorithm for multi-gpu.

**Comment by 1234273** [comment]
I got it.Thank you very much!
