### ISSUE TITLE
File path issue

### ISSUE THREAD

**Issue by jishenghuang** [nii-yamagishilab/Capsule-Forensics-v2#17]
![image](https://user-images.githubusercontent.com/94595843/166427126-a4014f03-00c3-4392-94ba-8e4835f02916.png)
At the time of running create_dataset_Original.py, this problem arose, how should it be solved

**Comment by jishenghuang** [comment]
> ![image](https://user-images.githubusercontent.com/94595843/166427126-a4014f03-00c3-4392-94ba-8e4835f02916.png) At the time of running create_dataset_Original.py, this problem arose, how should it be solved

**Comment by honghuy127** [comment]
Hi, you should provide the path to the split file, which could be found [here](https://github.com/ondyari/FaceForensics/tree/master/dataset/splits).
