### ISSUE TITLE
Why concatenate image_cropped and mask_cropped?

### ISSUE THREAD

**Issue by FrazierLei** [nii-yamagishilab/Capsule-Forensics-v2#19]
Hi！After `image_cropped = np.concatenate((image_cropped, mask_cropped), axis=1)`, the saved image is like
![Snipaste_2022-05-10_14-21-00](https://user-images.githubusercontent.com/43394641/167561565-f7de198b-465c-498e-b7e3-2044cdfd7752.png)

Why would you concatenate these two parts? Thanks!

**Comment by honghuy127** [comment]
Ah, this is a bug due to copying problem. I removed those lines.

**Comment by FrazierLei** [comment]
> Ah, this is a bug due to copying problem. I removed those lines.

😂😂😂
Thanks for your well-organized code and quick reply!
