### ISSUE TITLE
Face Forensic dataset and pretrained model

### ISSUE THREAD

**Issue by amuchand47** [nii-yamagishilab/Capsule-Forensics-v2#2]
Please provide face forensic dataset and trained model as soon as possible.

**Comment by honghuy127** [comment]
You could find the dataset [here](https://github.com/ondyari/FaceForensics).

The checkpoints could be found in the [checkpoints folder](https://github.com/nii-yamagishilab/Capsule-Forensics-v2/tree/master/checkpoints).

**Comment by znshi** [comment]
hi,
which compression levels (or all three levels) is used in the training and evaluating?

**Comment by honghuy127** [comment]
We used three levels for training and evaluating.
