### ISSUE TITLE
Testing Video Samples using test_vid_multiclass_ffpp.py

### ISSUE THREAD

**Issue by Jayakrishnan-A** [nii-yamagishilab/Capsule-Forensics-v2#20]
Hi, I was trying to run test_vid_multiclass_ffpp.py, for test some videos. I am getting some errors from classify_frames function. Line no 140 is looking for " img_ext_lst". Even though I have changed it to vid_ext_lst, it is getting error from line no 161 ( **_test_img = transform_fwd(Image.open(os.path.join(path, file_lst[i])))_**). Image.read. Kindly look in to this . Thanks.

**Comment by honghuy127** [comment]
Hi, this scripts take video frames instead of video.
Please refer [this one](https://github.com/nii-yamagishilab/Capsule-Forensics-v2/issues/8) for more information.
