### ISSUE TITLE
What is folder structure inside /databases/faceforensicspp/train

### ISSUE THREAD

**Issue by neverUseThisName** [nii-yamagishilab/Capsule-Forensics-v2#5]
There are 4 folders, what kind of data to put in? Do I have to know the kind of forgery for every piece of data?

**Comment by honghuy127** [comment]
Hi, as default, you could put Real, DeepFakes, Face2Face, and FaceSwap into them.

However, I use the default data folder dataloader from PyTorch, so you can put any kind of forgery on them. The easiest way to do that is to create two folders: 0_real and 1_fake.

**Comment by neverUseThisName** [comment]
I understand, thanks.

> Hi, as default, you could put Real, DeepFakes, Face2Face, and FaceSwap into them.
> 
> However, I use the default data folder dataloader from PyTorch, so you can put any kind of forgery on them. The easiest way to do that is to create two folders: 0_real and 1_fake.
