### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by AnniRen** [nii-yamagishilab/Capsule-Forensics-v2#8]
Traceback (most recent call last):
  File "test_vid_multiclass_ffpp.py", line 224, in <module>
    count_vid, correct = classify_frames(vgg_ext, model, path_real, 0)
TypeError: cannot unpack non-iterable NoneType object

**Comment by wasim004** [comment]
Getting same error.
Please address the solution.
Thanks!

**Comment by honghuy127** [comment]
Could you please give me more information about this error? The above error message is too short.

**Comment by wasim004** [comment]
Hi, 
This error happens only in evaluating `test_vid_binary_ffpp.py` and `test_vid_multiclass_ffpp.py` as shown.
Thanks!

![issue](https://user-images.githubusercontent.com/24964488/154834378-8ffd79b3-61bf-481f-979f-ea812c9a7695.png)

**Comment by honghuy127** [comment]
Hi, I ran the script and there was no problem in my machine.

Did you follow the [directory structure](https://github.com/nii-yamagishilab/Capsule-Forensics-v2/tree/master/databases/faceforensicspp/test) which I provided?

Furthermore, you need to follow the naming format, for example:

```
1_deepfakes/c0_000_003_0_deepfakes.jpg
1_deepfakes/c0_000_003_1_deepfakes.jpg
1_deepfakes/c0_000_003_2_deepfakes.jpg
1_deepfakes/c0_000_003_3_deepfakes.jpg
1_deepfakes/c0_000_003_4_deepfakes.jpg
1_deepfakes/c0_000_003_5_deepfakes.jpg
1_deepfakes/c0_000_003_6_deepfakes.jpg
1_deepfakes/c0_000_003_7_deepfakes.jpg
1_deepfakes/c0_000_003_8_deepfakes.jpg
1_deepfakes/c0_000_003_9_deepfakes.jpg
1_deepfakes/c0_003_000_0_deepfakes.jpg
1_deepfakes/c0_003_000_1_deepfakes.jpg
1_deepfakes/c0_003_000_2_deepfakes.jpg
1_deepfakes/c0_003_000_3_deepfakes.jpg
1_deepfakes/c0_003_000_4_deepfakes.jpg
1_deepfakes/c0_003_000_5_deepfakes.jpg
1_deepfakes/c0_003_000_6_deepfakes.jpg
1_deepfakes/c0_003_000_7_deepfakes.jpg
1_deepfakes/c0_003_000_8_deepfakes.jpg
1_deepfakes/c0_003_000_9_deepfakes.jpg
```

Could you please try to debug your script in your side?
If it is difficult, you can write your own script by referring to the `test_vid_multiclass_ffpp.py `script.

**Comment by wasim004** [comment]
Hi,
Yes I follow the same directory structure.

![folders](https://user-images.githubusercontent.com/24964488/154835803-4769f98b-3183-4ad6-b30b-fc52790d68b9.png)

**Comment by wasim004** [comment]
inside the folders I have placed concerned images of each video.
![images](https://user-images.githubusercontent.com/24964488/154835883-1b27f2ad-323e-4411-a997-cbf6464a23d3.png)

**Comment by wasim004** [comment]
I guess if we want to run any of  `test_vid_ffpp.py` for videos, we must make a video file of those images in any of the following formats as mentioned in the code.
`vid_ext_lst = ('avi', 'mkv', 'mpeg', 'mpg', 'mp4')`.

Am I right?

**Comment by wasim004** [comment]
Can you share with me your script for `extracting faces/frames from videos and then make a video file of those frames`. Because I can't figure it out how many frames should I extract from each video etc and so on.

**Comment by wasim004** [comment]
I have successfully trained model for `train_binary_ffpp.py` and `train_multiclass_ffpp.py`, and I got the following results.

![multiclass_train_test](https://user-images.githubusercontent.com/24964488/154836695-295d86ab-a5ba-47fd-b4d4-f70c891ef9b2.png)
![Train+Test](https://user-images.githubusercontent.com/24964488/154836705-2d95a465-857d-4e5e-8a43-07d630c9280f.png)

**Comment by honghuy127** [comment]
Hi, thank you for the update.

I uploaded the scripts for data preprocessing at `datascripts` directory.

**Comment by wasim004** [comment]
Thank You so much..!
